version: '3.9'

services:
  suitecx-react-app:
    image: registry.questionpro.net/suitecx/ca/frontend:${TAG:-latest}
    container_name: journeymanagement_frontend_ca
    restart: always
    env_file:
      - /opt/.env_journeymanagement_frontend_ca
    ports:
      - "3025:3003"
