version: '3.9'

services:
  suitecx-react-app:
    image: registry.questionpro.net/suitecx/au/frontend:${TAG:-latest}
    container_name: journeymanagement_frontend_au
    restart: always
    env_file:
      - /opt/.env_journeymanagement_frontend_au
    ports:
      - "3024:3003"
