version: '3.9'

services:
  suitecx-react-app:
    image: registry.questionpro.net/suitecx/staging/frontend:${TAG:-latest}
    container_name: suitecx-frontend-staging
    restart: always
    env_file:
      - /opt/.env_suitecx_staging_frontend
    network_mode: host
