version: '3.9'

services:
  suitecx-react-app:
    image: registry.questionpro.net/suitecx/ksa/frontend:${TAG:-latest}
    container_name: journeymanagement_frontend_ksa
    restart: always
    env_file:
      - /opt/.env_journeymanagement_frontend_ksa
    ports:
      - "3026:3003"
