/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthorizationCallbackImport } from './routes/authorization/callback'
import { Route as AuthenticatedSecondarySidebarLayoutImport } from './routes/_authenticated/_secondary-sidebar-layout'
import { Route as AuthenticatedPrimarySidebarLayoutImport } from './routes/_authenticated/_primary-sidebar-layout'
import { Route as AuthenticatedWorkspacesIndexImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedPrimarySidebarLayoutUsersIndexImport } from './routes/_authenticated/_primary-sidebar-layout/users/index'
import { Route as AuthenticatedPrimarySidebarLayoutSettingsIndexImport } from './routes/_authenticated/_primary-sidebar-layout/settings/index'
import { Route as AuthenticatedPrimarySidebarLayoutAdminIndexImport } from './routes/_authenticated/_primary-sidebar-layout/admin/index'
import { Route as AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport } from './routes/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId'
import { Route as AuthenticatedSecondarySidebarLayoutBoardBoardIdImport } from './routes/_authenticated/_secondary-sidebar-layout/board/$boardId'
import { Route as AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexImport } from './routes/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-groups/index'
import { Route as AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexImport } from './routes/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/interviews/index'
import { Route as AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexImport } from './routes/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/boards/index'
import { Route as AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexImport } from './routes/_authenticated/_secondary-sidebar-layout/board/$boardId/journies/index'
import { Route as AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexImport } from './routes/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona/$personaId/index'
import { Route as AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexImport } from './routes/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-group/$personaGroupId/index'
import { Route as AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexImport } from './routes/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/outcome/$outcomeId/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthorizationCallbackRoute = AuthorizationCallbackImport.update({
  id: '/authorization/callback',
  path: '/authorization/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSecondarySidebarLayoutRoute =
  AuthenticatedSecondarySidebarLayoutImport.update({
    id: '/_secondary-sidebar-layout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPrimarySidebarLayoutRoute =
  AuthenticatedPrimarySidebarLayoutImport.update({
    id: '/_primary-sidebar-layout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPrimarySidebarLayoutUsersIndexRoute =
  AuthenticatedPrimarySidebarLayoutUsersIndexImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedPrimarySidebarLayoutRoute,
  } as any)

const AuthenticatedPrimarySidebarLayoutSettingsIndexRoute =
  AuthenticatedPrimarySidebarLayoutSettingsIndexImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedPrimarySidebarLayoutRoute,
  } as any)

const AuthenticatedPrimarySidebarLayoutAdminIndexRoute =
  AuthenticatedPrimarySidebarLayoutAdminIndexImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedPrimarySidebarLayoutRoute,
  } as any)

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute =
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => AuthenticatedSecondarySidebarLayoutRoute,
  } as any)

const AuthenticatedSecondarySidebarLayoutBoardBoardIdRoute =
  AuthenticatedSecondarySidebarLayoutBoardBoardIdImport.update({
    id: '/board/$boardId',
    path: '/board/$boardId',
    getParentRoute: () => AuthenticatedSecondarySidebarLayoutRoute,
  } as any)

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexRoute =
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexImport.update(
    {
      id: '/persona-groups/',
      path: '/persona-groups/',
      getParentRoute: () =>
        AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute,
    } as any,
  )

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexRoute =
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexImport.update(
    {
      id: '/interviews/',
      path: '/interviews/',
      getParentRoute: () =>
        AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute,
    } as any,
  )

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexRoute =
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexImport.update(
    {
      id: '/boards/',
      path: '/boards/',
      getParentRoute: () =>
        AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute,
    } as any,
  )

const AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexRoute =
  AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexImport.update({
    id: '/journies/',
    path: '/journies/',
    getParentRoute: () => AuthenticatedSecondarySidebarLayoutBoardBoardIdRoute,
  } as any)

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexRoute =
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexImport.update(
    {
      id: '/persona/$personaId/',
      path: '/persona/$personaId/',
      getParentRoute: () =>
        AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute,
    } as any,
  )

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexRoute =
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexImport.update(
    {
      id: '/persona-group/$personaGroupId/',
      path: '/persona-group/$personaGroupId/',
      getParentRoute: () =>
        AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute,
    } as any,
  )

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexRoute =
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexImport.update(
    {
      id: '/outcome/$outcomeId/',
      path: '/outcome/$outcomeId/',
      getParentRoute: () =>
        AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_primary-sidebar-layout': {
      id: '/_authenticated/_primary-sidebar-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedPrimarySidebarLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_secondary-sidebar-layout': {
      id: '/_authenticated/_secondary-sidebar-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/authorization/callback': {
      id: '/authorization/callback'
      path: '/authorization/callback'
      fullPath: '/authorization/callback'
      preLoaderRoute: typeof AuthorizationCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_secondary-sidebar-layout/board/$boardId': {
      id: '/_authenticated/_secondary-sidebar-layout/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutImport
    }
    '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId': {
      id: '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutImport
    }
    '/_authenticated/_primary-sidebar-layout/admin/': {
      id: '/_authenticated/_primary-sidebar-layout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedPrimarySidebarLayoutAdminIndexImport
      parentRoute: typeof AuthenticatedPrimarySidebarLayoutImport
    }
    '/_authenticated/_primary-sidebar-layout/settings/': {
      id: '/_authenticated/_primary-sidebar-layout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedPrimarySidebarLayoutSettingsIndexImport
      parentRoute: typeof AuthenticatedPrimarySidebarLayoutImport
    }
    '/_authenticated/_primary-sidebar-layout/users/': {
      id: '/_authenticated/_primary-sidebar-layout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedPrimarySidebarLayoutUsersIndexImport
      parentRoute: typeof AuthenticatedPrimarySidebarLayoutImport
    }
    '/_authenticated/_secondary-sidebar-layout/board/$boardId/journies/': {
      id: '/_authenticated/_secondary-sidebar-layout/board/$boardId/journies/'
      path: '/journies'
      fullPath: '/board/$boardId/journies'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdImport
    }
    '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/boards/': {
      id: '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/boards/'
      path: '/boards'
      fullPath: '/workspace/$workspaceId/boards'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport
    }
    '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/interviews/': {
      id: '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/interviews/'
      path: '/interviews'
      fullPath: '/workspace/$workspaceId/interviews'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport
    }
    '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-groups/': {
      id: '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-groups/'
      path: '/persona-groups'
      fullPath: '/workspace/$workspaceId/persona-groups'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport
    }
    '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/outcome/$outcomeId/': {
      id: '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/outcome/$outcomeId/'
      path: '/outcome/$outcomeId'
      fullPath: '/workspace/$workspaceId/outcome/$outcomeId'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport
    }
    '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-group/$personaGroupId/': {
      id: '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-group/$personaGroupId/'
      path: '/persona-group/$personaGroupId'
      fullPath: '/workspace/$workspaceId/persona-group/$personaGroupId'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport
    }
    '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona/$personaId/': {
      id: '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona/$personaId/'
      path: '/persona/$personaId'
      fullPath: '/workspace/$workspaceId/persona/$personaId'
      preLoaderRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexImport
      parentRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedPrimarySidebarLayoutRouteChildren {
  AuthenticatedPrimarySidebarLayoutAdminIndexRoute: typeof AuthenticatedPrimarySidebarLayoutAdminIndexRoute
  AuthenticatedPrimarySidebarLayoutSettingsIndexRoute: typeof AuthenticatedPrimarySidebarLayoutSettingsIndexRoute
  AuthenticatedPrimarySidebarLayoutUsersIndexRoute: typeof AuthenticatedPrimarySidebarLayoutUsersIndexRoute
}

const AuthenticatedPrimarySidebarLayoutRouteChildren: AuthenticatedPrimarySidebarLayoutRouteChildren =
  {
    AuthenticatedPrimarySidebarLayoutAdminIndexRoute:
      AuthenticatedPrimarySidebarLayoutAdminIndexRoute,
    AuthenticatedPrimarySidebarLayoutSettingsIndexRoute:
      AuthenticatedPrimarySidebarLayoutSettingsIndexRoute,
    AuthenticatedPrimarySidebarLayoutUsersIndexRoute:
      AuthenticatedPrimarySidebarLayoutUsersIndexRoute,
  }

const AuthenticatedPrimarySidebarLayoutRouteWithChildren =
  AuthenticatedPrimarySidebarLayoutRoute._addFileChildren(
    AuthenticatedPrimarySidebarLayoutRouteChildren,
  )

interface AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteChildren {
  AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexRoute: typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexRoute
}

const AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteChildren: AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteChildren =
  {
    AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexRoute:
      AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexRoute,
  }

const AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteWithChildren =
  AuthenticatedSecondarySidebarLayoutBoardBoardIdRoute._addFileChildren(
    AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteChildren,
  )

interface AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteChildren {
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexRoute
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexRoute
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexRoute
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexRoute
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexRoute
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexRoute
}

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteChildren: AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteChildren =
  {
    AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexRoute:
      AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexRoute,
    AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexRoute:
      AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexRoute,
    AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexRoute:
      AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexRoute,
    AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexRoute:
      AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexRoute,
    AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexRoute:
      AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexRoute,
    AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexRoute:
      AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexRoute,
  }

const AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteWithChildren =
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute._addFileChildren(
    AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteChildren,
  )

interface AuthenticatedSecondarySidebarLayoutRouteChildren {
  AuthenticatedSecondarySidebarLayoutBoardBoardIdRoute: typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteWithChildren
  AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute: typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteWithChildren
}

const AuthenticatedSecondarySidebarLayoutRouteChildren: AuthenticatedSecondarySidebarLayoutRouteChildren =
  {
    AuthenticatedSecondarySidebarLayoutBoardBoardIdRoute:
      AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteWithChildren,
    AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRoute:
      AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteWithChildren,
  }

const AuthenticatedSecondarySidebarLayoutRouteWithChildren =
  AuthenticatedSecondarySidebarLayoutRoute._addFileChildren(
    AuthenticatedSecondarySidebarLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPrimarySidebarLayoutRoute: typeof AuthenticatedPrimarySidebarLayoutRouteWithChildren
  AuthenticatedSecondarySidebarLayoutRoute: typeof AuthenticatedSecondarySidebarLayoutRouteWithChildren
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPrimarySidebarLayoutRoute:
    AuthenticatedPrimarySidebarLayoutRouteWithChildren,
  AuthenticatedSecondarySidebarLayoutRoute:
    AuthenticatedSecondarySidebarLayoutRouteWithChildren,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedSecondarySidebarLayoutRouteWithChildren
  '/authorization/callback': typeof AuthorizationCallbackRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/board/$boardId': typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteWithChildren
  '/workspace/$workspaceId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteWithChildren
  '/admin': typeof AuthenticatedPrimarySidebarLayoutAdminIndexRoute
  '/settings': typeof AuthenticatedPrimarySidebarLayoutSettingsIndexRoute
  '/users': typeof AuthenticatedPrimarySidebarLayoutUsersIndexRoute
  '/board/$boardId/journies': typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexRoute
  '/workspace/$workspaceId/boards': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexRoute
  '/workspace/$workspaceId/interviews': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexRoute
  '/workspace/$workspaceId/persona-groups': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexRoute
  '/workspace/$workspaceId/outcome/$outcomeId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexRoute
  '/workspace/$workspaceId/persona-group/$personaGroupId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexRoute
  '/workspace/$workspaceId/persona/$personaId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedSecondarySidebarLayoutRouteWithChildren
  '/authorization/callback': typeof AuthorizationCallbackRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/board/$boardId': typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteWithChildren
  '/workspace/$workspaceId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteWithChildren
  '/admin': typeof AuthenticatedPrimarySidebarLayoutAdminIndexRoute
  '/settings': typeof AuthenticatedPrimarySidebarLayoutSettingsIndexRoute
  '/users': typeof AuthenticatedPrimarySidebarLayoutUsersIndexRoute
  '/board/$boardId/journies': typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexRoute
  '/workspace/$workspaceId/boards': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexRoute
  '/workspace/$workspaceId/interviews': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexRoute
  '/workspace/$workspaceId/persona-groups': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexRoute
  '/workspace/$workspaceId/outcome/$outcomeId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexRoute
  '/workspace/$workspaceId/persona-group/$personaGroupId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexRoute
  '/workspace/$workspaceId/persona/$personaId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_primary-sidebar-layout': typeof AuthenticatedPrimarySidebarLayoutRouteWithChildren
  '/_authenticated/_secondary-sidebar-layout': typeof AuthenticatedSecondarySidebarLayoutRouteWithChildren
  '/authorization/callback': typeof AuthorizationCallbackRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/_secondary-sidebar-layout/board/$boardId': typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdRouteWithChildren
  '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdRouteWithChildren
  '/_authenticated/_primary-sidebar-layout/admin/': typeof AuthenticatedPrimarySidebarLayoutAdminIndexRoute
  '/_authenticated/_primary-sidebar-layout/settings/': typeof AuthenticatedPrimarySidebarLayoutSettingsIndexRoute
  '/_authenticated/_primary-sidebar-layout/users/': typeof AuthenticatedPrimarySidebarLayoutUsersIndexRoute
  '/_authenticated/_secondary-sidebar-layout/board/$boardId/journies/': typeof AuthenticatedSecondarySidebarLayoutBoardBoardIdJourniesIndexRoute
  '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/boards/': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdBoardsIndexRoute
  '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/interviews/': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdInterviewsIndexRoute
  '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-groups/': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupsIndexRoute
  '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/outcome/$outcomeId/': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdOutcomeOutcomeIdIndexRoute
  '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-group/$personaGroupId/': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaGroupPersonaGroupIdIndexRoute
  '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona/$personaId/': typeof AuthenticatedSecondarySidebarLayoutWorkspaceWorkspaceIdPersonaPersonaIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/authorization/callback'
    | '/workspaces'
    | '/board/$boardId'
    | '/workspace/$workspaceId'
    | '/admin'
    | '/settings'
    | '/users'
    | '/board/$boardId/journies'
    | '/workspace/$workspaceId/boards'
    | '/workspace/$workspaceId/interviews'
    | '/workspace/$workspaceId/persona-groups'
    | '/workspace/$workspaceId/outcome/$outcomeId'
    | '/workspace/$workspaceId/persona-group/$personaGroupId'
    | '/workspace/$workspaceId/persona/$personaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/authorization/callback'
    | '/workspaces'
    | '/board/$boardId'
    | '/workspace/$workspaceId'
    | '/admin'
    | '/settings'
    | '/users'
    | '/board/$boardId/journies'
    | '/workspace/$workspaceId/boards'
    | '/workspace/$workspaceId/interviews'
    | '/workspace/$workspaceId/persona-groups'
    | '/workspace/$workspaceId/outcome/$outcomeId'
    | '/workspace/$workspaceId/persona-group/$personaGroupId'
    | '/workspace/$workspaceId/persona/$personaId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_primary-sidebar-layout'
    | '/_authenticated/_secondary-sidebar-layout'
    | '/authorization/callback'
    | '/_authenticated/workspaces/'
    | '/_authenticated/_secondary-sidebar-layout/board/$boardId'
    | '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId'
    | '/_authenticated/_primary-sidebar-layout/admin/'
    | '/_authenticated/_primary-sidebar-layout/settings/'
    | '/_authenticated/_primary-sidebar-layout/users/'
    | '/_authenticated/_secondary-sidebar-layout/board/$boardId/journies/'
    | '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/boards/'
    | '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/interviews/'
    | '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-groups/'
    | '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/outcome/$outcomeId/'
    | '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-group/$personaGroupId/'
    | '/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona/$personaId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthorizationCallbackRoute: typeof AuthorizationCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthorizationCallbackRoute: AuthorizationCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/authorization/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_primary-sidebar-layout",
        "/_authenticated/_secondary-sidebar-layout",
        "/_authenticated/workspaces/"
      ]
    },
    "/_authenticated/_primary-sidebar-layout": {
      "filePath": "_authenticated/_primary-sidebar-layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_primary-sidebar-layout/admin/",
        "/_authenticated/_primary-sidebar-layout/settings/",
        "/_authenticated/_primary-sidebar-layout/users/"
      ]
    },
    "/_authenticated/_secondary-sidebar-layout": {
      "filePath": "_authenticated/_secondary-sidebar-layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_secondary-sidebar-layout/board/$boardId",
        "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId"
      ]
    },
    "/authorization/callback": {
      "filePath": "authorization/callback.tsx"
    },
    "/_authenticated/workspaces/": {
      "filePath": "_authenticated/workspaces/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_secondary-sidebar-layout/board/$boardId": {
      "filePath": "_authenticated/_secondary-sidebar-layout/board/$boardId.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout",
      "children": [
        "/_authenticated/_secondary-sidebar-layout/board/$boardId/journies/"
      ]
    },
    "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId": {
      "filePath": "_authenticated/_secondary-sidebar-layout/workspace/$workspaceId.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout",
      "children": [
        "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/boards/",
        "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/interviews/",
        "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-groups/",
        "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/outcome/$outcomeId/",
        "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-group/$personaGroupId/",
        "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona/$personaId/"
      ]
    },
    "/_authenticated/_primary-sidebar-layout/admin/": {
      "filePath": "_authenticated/_primary-sidebar-layout/admin/index.tsx",
      "parent": "/_authenticated/_primary-sidebar-layout"
    },
    "/_authenticated/_primary-sidebar-layout/settings/": {
      "filePath": "_authenticated/_primary-sidebar-layout/settings/index.tsx",
      "parent": "/_authenticated/_primary-sidebar-layout"
    },
    "/_authenticated/_primary-sidebar-layout/users/": {
      "filePath": "_authenticated/_primary-sidebar-layout/users/index.tsx",
      "parent": "/_authenticated/_primary-sidebar-layout"
    },
    "/_authenticated/_secondary-sidebar-layout/board/$boardId/journies/": {
      "filePath": "_authenticated/_secondary-sidebar-layout/board/$boardId/journies/index.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout/board/$boardId"
    },
    "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/boards/": {
      "filePath": "_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/boards/index.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId"
    },
    "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/interviews/": {
      "filePath": "_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/interviews/index.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId"
    },
    "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-groups/": {
      "filePath": "_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-groups/index.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId"
    },
    "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/outcome/$outcomeId/": {
      "filePath": "_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/outcome/$outcomeId/index.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId"
    },
    "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-group/$personaGroupId/": {
      "filePath": "_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona-group/$personaGroupId/index.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId"
    },
    "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona/$personaId/": {
      "filePath": "_authenticated/_secondary-sidebar-layout/workspace/$workspaceId/persona/$personaId/index.tsx",
      "parent": "/_authenticated/_secondary-sidebar-layout/workspace/$workspaceId"
    }
  }
}
ROUTE_MANIFEST_END */
