/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AuthenticatedImport } from "./routes/_authenticated";
import { Route as IndexImport } from "./routes/index";
import { Route as AuthorizationCallbackImport } from "./routes/authorization/callback";
import { Route as AuthenticatedWorkspacesImport } from "./routes/_authenticated/workspaces";

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AuthorizationCallbackRoute = AuthorizationCallbackImport.update({
  id: "/authorization/callback",
  path: "/authorization/callback",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesImport.update({
  id: "/workspaces",
  path: "/workspaces",
  getParentRoute: () => AuthenticatedRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/workspaces": {
      id: "/_authenticated/workspaces";
      path: "/workspaces";
      fullPath: "/workspaces";
      preLoaderRoute: typeof AuthenticatedWorkspacesImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/authorization/callback": {
      id: "/authorization/callback";
      path: "/authorization/callback";
      fullPath: "/authorization/callback";
      preLoaderRoute: typeof AuthorizationCallbackImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/workspaces": typeof AuthenticatedWorkspacesRoute;
  "/authorization/callback": typeof AuthorizationCallbackRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/workspaces": typeof AuthenticatedWorkspacesRoute;
  "/authorization/callback": typeof AuthorizationCallbackRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/_authenticated/workspaces": typeof AuthenticatedWorkspacesRoute;
  "/authorization/callback": typeof AuthorizationCallbackRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "" | "/workspaces" | "/authorization/callback";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "" | "/workspaces" | "/authorization/callback";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/_authenticated/workspaces"
    | "/authorization/callback";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  AuthorizationCallbackRoute: typeof AuthorizationCallbackRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthorizationCallbackRoute: AuthorizationCallbackRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/authorization/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/workspaces"
      ]
    },
    "/_authenticated/workspaces": {
      "filePath": "_authenticated/workspaces.tsx",
      "parent": "/_authenticated"
    },
    "/authorization/callback": {
      "filePath": "authorization/callback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
